[ALPINAWEB-164] Add bottom up button
netlogix/nlxBackToTopButton pull request #2
Opened 2021-11-22 09:13 UTC by TheBreaken

2021-11-23 08:24 UTC, sd-lueckel requested changes

2021-11-23 08:24 UTC, sd-lueckel commented on Resources/frontend/js/jquery.button-back-to-top.js
> +    $.plugin('sdScrollTop', {
```suggestion
    $.plugin('nlxScrollTop', {
```

2021-11-23 08:24 UTC, sd-lueckel commented on Resources/frontend/js/jquery.button-back-to-top.js
> +    window.StateManager.addPlugin('body', 'sdScrollTop');
```suggestion
    window.StateManager.addPlugin('body', 'nlxScrollTop');
```

2021-11-24 08:26 UTC, TheBreaken commented on Resources/frontend/js/jquery.button-back-to-top.js
> +    $.plugin('sdScrollTop', {
Done

2021-11-24 08:26 UTC, TheBreaken commented on Resources/frontend/js/jquery.button-back-to-top.js
> +    window.StateManager.addPlugin('body', 'sdScrollTop');
Done

2021-11-24 08:27 UTC, sd-lueckel approved these changes

2021-11-24 08:27 UTC, merged